services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio-admin
      MINIO_ROOT_PASSWORD: minio-admin-password
    command: server /data --console-address ":9001"
    networks:
      - backend

  echo-app:
    build:
      context: ./go-service/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_USER: postgres
      DB_PASSWORD: test
      DB_NAME: prism
      DB_PORT: 5432
    depends_on:
      database:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - backend
    restart: unless-stopped

  database:
    image: postgres:18.0
    container_name: prism_db
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test        # ✅ correct var name
      POSTGRES_DB: prism
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d prism"]
      interval: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432" 
    volumes:
      - database-data:/var/lib/postgresql
    networks:
      - backend
    restart: unless-stopped

  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - echo-app
    environment:
      - NODE_ENV=development
      - AUTH_DISCORD_ID=test-discord-client-id
      - AUTH_DISCORD_SECRET=test-discord-client-secret
      - DATABASE_URL=postgresql://postgres:test@database:5432/prism
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    networks:
      - backend

volumes:
  database-data:

networks:
  backend:
