services:
  echo-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_USER: postgres
      DB_PASSWORD: test
      DB_NAME: prism
      DB_PORT: 5432
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped

  database:
    image: postgres:18.0
    container_name: prism_db
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test        # ✅ correct var name
      POSTGRES_DB: prism
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d prism"]
      interval: 5s
      retries: 5
      start_period: 10s
    volumes:
      - database-data:/var/lib/postgresql
    networks:
      - backend
    restart: unless-stopped


volumes:
  database-data:

networks:
  backend:
    driver: bridge